from abc import ABC, abstractmethod
from typing import Optional
from uuid import UUID
from src.domain.user.user import User

class IUserRepository(ABC):
    """
    Interface for User data access.
    Supports operations required by ARD sections 2.2.1 (Register) and 2.2.2 (Login).
    """

    @abstractmethod
    async def save(self, user: User) -> User:
        """
        Save a user entity to the storage (Create or Update).
        The user object already contains the ID generated by the Service/Entity.
        """
        pass

    @abstractmethod
    async def get_by_email(self, email: str) -> Optional[User]:
        """
        Find a user by their email address.
        Returns a User entity object if found, else None.
        """
        pass

    @abstractmethod
    async def get_by_id(self, user_id: UUID) -> Optional[User]:
        """
        Find a user by their unique UUID.
        Returns a User entity object if found, else None.
        """
        pass

    @abstractmethod
    async def get_names_by_ids(self, user_ids: list[UUID]) -> dict[UUID, str]:
        """
        Retrieve a mapping of user IDs to their names for a list of user IDs.
        Returns a dictionary where keys are user UUIDs and values are user names.
        """
        pass

    @abstractmethod
    async def update_push_token(self, user_id: UUID, new_push_token: str) -> Optional[User]:
        """
        Update the push notification token for a user.
        Returns the updated User entity if successful, else None if user not found.
        """
        pass