"""add push token to users

Revision ID: 5e06c3ab24f6
Revises: 
Create Date: 2026-03-11 13:08:41.353061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e06c3ab24f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_items',
    sa.Column('Barcode', sa.String(), nullable=False),
    sa.Column('Chain', sa.String(), nullable=False),
    sa.Column('ItemName', sa.String(), nullable=False),
    sa.Column('ManufacturerName', sa.String(), nullable=True),
    sa.Column('UnitOfMeasure', sa.String(), nullable=True),
    sa.Column('QtyInPackage', sa.String(), nullable=True),
    sa.Column('LastUpdate', sa.DateTime(), nullable=True),
    sa.Column('SuggestedStorageCategory', sa.String(), nullable=True),
    sa.Column('AverageWeight', sa.Float(), nullable=True),
    sa.Column('SampleSize', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Barcode', 'Chain')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('push_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('homes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('join_code', sa.String(), nullable=True),
    sa.Column('expiration_range', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homes_id'), 'homes', ['id'], unique=False)
    op.create_index(op.f('ix_homes_join_code'), 'homes', ['join_code'], unique=False)
    op.create_table('home_join_requests',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('home_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['home_id'], ['homes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'home_id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('home_id', sa.String(), nullable=True),
    sa.Column('original_name', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['home_id'], ['homes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('user_home',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('home_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['home_id'], ['homes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'home_id')
    )
    op.create_table('product_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_items_id'), 'product_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_items_id'), table_name='product_items')
    op.drop_table('product_items')
    op.drop_table('user_home')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    op.drop_table('home_join_requests')
    op.drop_index(op.f('ix_homes_join_code'), table_name='homes')
    op.drop_index(op.f('ix_homes_id'), table_name='homes')
    op.drop_table('homes')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('catalog_items')
    # ### end Alembic commands ###
