from abc import ABC, abstractmethod
from typing import Optional
from uuid import UUID
from domain.user import User

class IUserRepository(ABC):
    """
    Interface for User data access.
    Supports operations required by ARD sections 2.2.1 (Register) and 2.2.2 (Login).
    """

    @abstractmethod
    async def save(self, user: User) -> None:
        """
        Save a user entity to the storage (Create or Update).
        The user object already contains the ID generated by the Service/Entity.
        """
        pass

    @abstractmethod
    async def get_by_email(self, email: str) -> Optional[User]:
        """
        Find a user by their email address.
        Returns a User entity object if found, else None.
        """
        pass

    @abstractmethod
    async def get_by_id(self, user_id: UUID) -> Optional[User]:
        """
        Find a user by their unique UUID.
        Returns a User entity object if found, else None.
        """
        pass