import { StyleSheet, Platform } from "react-native";
import { type LocationKey as BaseLocation } from "@/src/hooks/shopping/useShoppingList";

export type SectionLocation = BaseLocation | "UNSORTED";

export const BRAND = {
  BG: "#F4F4F4",
  CARD: "#FFFFFF",
  BORDER: "#E5E7EB",
  TEXT: "#111827",
  MUTED: "#6B7280",
  PRIMARY: "#0284C7",
  PRIMARY_SOFT: "#E5F3FF",
  DANGER: "#DC2626",
  SUCCESS: "#16A34A",
  NOTE_LINE: "#E8EDF5",
};

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: BRAND.BG },
  center: { flex: 1, alignItems: "center", justifyContent: "center" },
  loadingText: { marginTop: 8, color: BRAND.MUTED, fontWeight: "700", fontSize: 13 },
  topBlock: { marginBottom: 14 },
  toggleCard: {
    backgroundColor: "rgba(255,255,255,0.92)",
    borderWidth: 1,
    borderColor: BRAND.BORDER,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginBottom: 12,
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  toggleTextWrap: { flex: 1, alignItems: "flex-end" },
  toggleTitle: { color: BRAND.TEXT, fontWeight: "900", fontSize: 14, textAlign: "right" },
  toggleSubtitle: { marginTop: 3, color: BRAND.MUTED, fontWeight: "700", fontSize: 11.5, textAlign: "right" },
  switchRoot: { width: 54, height: 32, borderRadius: 999, backgroundColor: "#D1D5DB", justifyContent: "center", paddingHorizontal: 4 },
  switchRootActive: { backgroundColor: BRAND.PRIMARY },
  switchThumb: { width: 24, height: 24, borderRadius: 999, backgroundColor: "#FFFFFF" },
  switchThumbActive: { transform: [{ translateX: 20 }] },
  summaryRow: { flexDirection: "row-reverse", gap: 10 },
  summaryCard: { flex: 1, backgroundColor: BRAND.CARD, borderRadius: 16, borderWidth: 1, borderColor: BRAND.BORDER, padding: 11, flexDirection: "row-reverse", alignItems: "center", gap: 10 },
  summaryIconWrap: { width: 34, height: 34, borderRadius: 11, backgroundColor: BRAND.PRIMARY_SOFT, alignItems: "center", justifyContent: "center" },
  summaryTitle: { color: BRAND.MUTED, fontWeight: "800", fontSize: 11, textAlign: "right" },
  summaryValue: { marginTop: 2, color: BRAND.TEXT, fontWeight: "900", fontSize: 16, textAlign: "right" },
  searchCard: { marginTop: 12, flexDirection: "row-reverse", alignItems: "center", gap: 8, paddingHorizontal: 12, paddingVertical: 11, borderRadius: 16, backgroundColor: "rgba(255,255,255,0.96)", borderWidth: 1, borderColor: BRAND.BORDER },
  searchInput: { flex: 1, color: BRAND.TEXT, fontWeight: "700", fontSize: 13 },
  sectionContainer: { marginBottom: 14 },
  sectionBlock: { marginBottom: 8 },
  locationHeader: { position: "relative", justifyContent: "center" },
  locationHeaderLine: { height: 1, backgroundColor: "#DCE4EF", width: "100%" },
  locationHeaderChip: { position: "absolute", alignSelf: "flex-end", flexDirection: "row-reverse", alignItems: "center", gap: 6, backgroundColor: BRAND.BG, paddingHorizontal: 10, height: 26, borderRadius: 999 },
  locationHeaderText: { color: BRAND.TEXT, fontWeight: "900", fontSize: 13 },
  notebookCard: { backgroundColor: "rgba(255,255,255,0.97)", borderRadius: 18, borderWidth: 1, borderColor: "#E8ECF3", overflow: "hidden", paddingVertical: 2 },
  separator: { height: 1, backgroundColor: BRAND.NOTE_LINE, marginHorizontal: 1 },
  noteRow: { minHeight: 56, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  noteRowPicked: { backgroundColor: "rgba(22,163,74,0.05)" },
  noteActions: { flexDirection: "row", alignItems: "center", gap: 6 },
  noteIconBtn: { width: 28, height: 28, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: "#F7FAFD", borderWidth: 1, borderColor: "#E7EDF5" },
  pickBtn: { width: 30, height: 30, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: "#F7FAFD", borderWidth: 1, borderColor: "#D7E7F7" },
  pickBtnActive: { backgroundColor: BRAND.SUCCESS, borderColor: BRAND.SUCCESS },
  noteQtyPill: { minWidth: 30, height: 28, paddingHorizontal: 8, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: "#F7FAFD", borderWidth: 1, borderColor: "#E7EDF5" },
  noteQtyText: { fontSize: 12, fontWeight: "900", color: BRAND.TEXT },
  noteTextWrap: { flex: 1, alignItems: "flex-end", marginLeft: 12 },
  noteTitleRow: { flexDirection: "row-reverse", alignItems: "center", gap: 8 },
  noteTitle: { fontSize: 14, fontWeight: "800", color: BRAND.TEXT, textAlign: "right" },
  noteTitlePicked: { textDecorationLine: "line-through", color: "#6B7280" },
  bottomActions: { position: "absolute", left: 0, right: 0, bottom: 58, paddingHorizontal: 16, paddingTop: 12, backgroundColor: "rgba(244,244,244,0.96)", borderTopWidth: 1, borderTopColor: "#E5E7EB", flexDirection: "row-reverse", gap: 10 },
  primaryBottomBtn: { flex: 1, height: 48, borderRadius: 15, backgroundColor: BRAND.PRIMARY, flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 8 },
  primaryBottomBtnFull: { width: "100%", height: 48, borderRadius: 15, backgroundColor: BRAND.PRIMARY, flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 8 },
  primaryBottomBtnText: { color: "#fff", fontWeight: "900", fontSize: 14 },
  secondaryBtn: { flex: 1, height: 48, borderRadius: 15, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: BRAND.BORDER, flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 8 },
  secondaryBtnText: { color: BRAND.TEXT, fontWeight: "900", fontSize: 14 },
  modalBackdrop: { flex: 1, backgroundColor: "rgba(17,24,39,0.35)", justifyContent: "flex-end", padding: 12 },
  modalCard: { backgroundColor: BRAND.CARD, borderRadius: 22, padding: 16, borderWidth: 1, borderColor: BRAND.BORDER, paddingBottom: Platform.OS === "ios" ? 30 : 16 },
  modalHandle: { alignSelf: "center", width: 42, height: 5, borderRadius: 999, backgroundColor: "#D1D5DB", marginBottom: 12 },
  modalHeader: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between" },
  modalTitle: { fontSize: 16, fontWeight: "900", color: BRAND.TEXT, textAlign: "right" },
  field: { marginBottom: 12 },
  label: { marginBottom: 6, color: BRAND.MUTED, fontWeight: "800", fontSize: 11.5, textAlign: "right" },
  input: { backgroundColor: "#FAFBFD", borderWidth: 1, borderColor: BRAND.BORDER, borderRadius: 13, paddingHorizontal: 12, paddingVertical: 11, color: BRAND.TEXT, fontWeight: "700", fontSize: 13 },
  locationWrap: { flexDirection: "row-reverse", flexWrap: "wrap", gap: 8, marginBottom: 14 },
  locationOption: { flexDirection: "row-reverse", alignItems: "center", gap: 8, paddingHorizontal: 11, paddingVertical: 9, borderRadius: 999, borderWidth: 1, borderColor: BRAND.BORDER, backgroundColor: "#fff" },
  locationOptionActive: { backgroundColor: "#F4FBFF", borderColor: "rgba(2,132,199,0.35)" },
  locationOptionText: { color: BRAND.MUTED, fontWeight: "800", fontSize: 12 },
  locationOptionTextActive: { color: BRAND.TEXT },
  primaryBtn: { marginTop: 4, height: 46, borderRadius: 14, backgroundColor: BRAND.PRIMARY, alignItems: "center", justifyContent: "center" },
  primaryBtnText: { color: "#fff", fontSize: 14, fontWeight: "900" },
  bottomBar: { position: "absolute", bottom: 0, left: 0, right: 0, backgroundColor: "rgba(255,255,255,0.92)", borderTopWidth: 1, borderTopColor: "#E5E7EB" },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: BRAND.BORDER,
    backgroundColor: BRAND.CARD,
    marginRight: 8,
  },
  chipText: {
    fontSize: 12,
    fontWeight: "800",
    color: BRAND.TEXT,
  },
});